language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-noodle' ]; then cd .. && eval "mv $currentfolder generator-noodle" && cd generator-noodle; fi
